-- 小程序文章表
CREATE TABLE `applet_article` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `type` varchar(50) DEFAULT NULL COMMENT '文章类型',
  `title` varchar(255) NOT NULL COMMENT '文章标题',
  `avatar` varchar(500) DEFAULT NULL COMMENT '文章头图',
  `summary` varchar(500) DEFAULT NULL COMMENT '文章摘要',
  `time` varchar(50) DEFAULT NULL COMMENT '发布时间',
  `label` varchar(100) DEFAULT NULL COMMENT '标签',
  `author` varchar(100) DEFAULT NULL COMMENT '作者',
  `status` varchar(10) DEFAULT NULL COMMENT '状态（1-发布）',
  `content_type` varchar(20) DEFAULT NULL COMMENT '内容类型（link-链接, html-富文本）',
  `content` text COMMENT '内容（链接地址或富文本内容）',
  `is_top` tinyint DEFAULT '0' COMMENT '是否置顶（0-否，1-是）',
  `view_count` int DEFAULT '0' COMMENT '浏览量',
  `like_count` int DEFAULT '0' COMMENT '点赞数',
  `sort` int DEFAULT '0' COMMENT '排序',
  `del_flag` varchar(10) DEFAULT '0' COMMENT '删除标识',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_id` bigint DEFAULT NULL COMMENT '创建人ID',
  `update_id` bigint DEFAULT NULL COMMENT '更新人ID',
  `publish_id` bigint DEFAULT NULL COMMENT '发布人ID',
  PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='小程序文章表';