<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>sz-boot-parent</artifactId>
        <groupId>com.sz</groupId>
        <version>${revision}</version>
    </parent>
    <artifactId>sz-module</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>sz-module-common</module>
        <module>sz-module-admin</module>
        <module>sz-module-generator</module>
    </modules>
</project>
