--liquibase formatted sql

--changeset 升职哦（sz）:20260411_1239
--以下为演示环境脚本，-- 仅供演示使用，实际业务请删除
ALTER TABLE `teacher_statistics` ADD COLUMN `has_invalid` enum('T','F') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'F' COMMENT '是否无效（枚举情况演示字段，包含mf枚举使用，excel枚举处理）' ;

--changeset 升职哦（sz）:20260501_1328
--以下为演示环境脚本，-- 仅供演示使用，实际业务请删除
UPDATE `teacher_statistics` SET `url` = '[{\"accessUrl\": null, \"objectKey\": \"teacher-attachments/template/teacher/20251021/bg1.png\", \"sceneCode\": \"teacher.attachment\", \"originName\": \"bg1.png\", \"contentType\": \"image/png\"}, {\"accessUrl\": null, \"objectKey\": \"teacher-attachments/template/teacher/20251021/bg7.png\", \"sceneCode\": \"teacher.attachment\", \"originName\": \"bg7.png\", \"contentType\": \"image/png\"}, {\"accessUrl\": null, \"objectKey\": \"teacher-attachments/template/teacher/20251021/bg10.png\", \"sceneCode\": \"teacher.attachment\", \"originName\": \"bg10.png\", \"contentType\": \"image/png\"}]', `has_invalid` = 'F' WHERE `id` = 25;
UPDATE `teacher_statistics` SET `url` = '[{\"accessUrl\": null, \"objectKey\": \"teacher-attachments/template/teacher/20251021/bg4.png\", \"sceneCode\": \"teacher.attachment\", \"originName\": \"bg4.png\", \"contentType\": \"image/png\"}, {\"accessUrl\": null, \"objectKey\": \"teacher-attachments/template/teacher/20251021/bg5.png\", \"sceneCode\": \"teacher.attachment\", \"originName\": \"bg5.png\", \"contentType\": \"image/png\"}, {\"accessUrl\": null, \"objectKey\": \"teacher-attachments/template/teacher/20251021/微信图片_20240420160033.jpg\", \"sceneCode\": \"teacher.attachment\", \"originName\": \"微信图片_20240420160033.jpg\", \"contentType\": \"image/jpeg\"}, {\"accessUrl\": null, \"objectKey\": \"teacher-attachments/template/teacher/20251021/教师统计.xlsx\", \"sceneCode\": \"teacher.attachment\", \"originName\": \"教师统计.xlsx\", \"contentType\": \"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\"}, {\"accessUrl\": null, \"objectKey\": \"teacher-attachments/template/teacher/20251021/sz-admin介绍.pdf\", \"sceneCode\": \"teacher.attachment\", \"originName\": \"sz-admin介绍.pdf\", \"contentType\": \"application/pdf\"}]', `has_invalid` = 'F' WHERE `id` = 26;
UPDATE `teacher_statistics` SET `has_invalid` = 'F', url = NULL where Id in  (22,23,24,27);