sz:
  # oss存储配置
  oss:
    # 支持S3协议的厂商
    provider: MINIO
    endpoint: 192.168.100.176:9000
    accessKey: 05balQ9A7aJYUwH8NOt1
    secretKey: YMhKoRbfHEgl3eDM2gDlu3hFSmBnB0cKZY2AzCrc
    # 全局存储桶
    bucketName: test
    domain: http://192.168.100.176:9000
    scheme: http
  # 场景资源配置
  resource:
    root: ./data
    default-storage-type: LOCAL
    security:
      allowed-exts: [jpg, jpeg, png, gif, bmp, webp, svg, ico, pdf, doc, docx, xls, xlsx, ppt, pptx, rtf, txt, csv, zip, rar, 7z, tar, gz, mp3, wav, ogg, mp4, mov, avi, wmv]
    max-size: 50MB
    scenes:
      # ========= 账户头像 - 本地模式 =========
      - code: admin.user.logo # 账户头像
        type: LOCAL
        serve-mode: DIRECT
        # base-url: http://127.0.0.1:7980/providers # nginx 代理
        base-url: http://127.0.0.1:9991/api/admin/resource/file/logo # java 服务代理
        path: logo
        naming: ORIGINAL
        path-strategy: BIZ_DATE
        exts: [svg, png, jpg, jpeg, webp, gif]
        max-size: 3
      # ========= 账户头像 - oss模式_private私有访问 =========
#      - code: admin.user.logo # 账户头像
#        type: OSS
#        serve-mode: PRESIGNED
#        bucket: client-logos
#        base-url: http://192.168.100.176:9000/client-logos # oss（minio）服务地址
#        naming: ORIGINAL
#        path-strategy: BIZ_DATE
#        exts: [svg, png, jpg, jpeg, webp, gif]
#        max-size: 3
      # ========= 账户头像 - oss模式_public公有访问 =========
#      - code: admin.user.logo # 账户头像
#        type: OSS
#        serve-mode: DIRECT
#        bucket: client-logos-public
#        base-url: http://192.168.100.176:9000/client-logos-public # oss（minio）服务地址
#        naming: UUID
#        path-strategy: BIZ_DATE
#        exts: [ svg, png, jpg, jpeg, webp, gif ]
#        max-size: 3
      # ========= 模版文件 - 本地模式 =========
      - code: template.excel
        type: LOCAL
        serve-mode: DIRECT
        path: template
        base-url: http://127.0.0.1:9991/api/admin/resource/file/template
        naming: ORIGINAL
        path-strategy: DATE
        exts: [ xls, xlsx ]
        max-size: 10
      # ========= 教师统计 - 附件 - 本地模式 =========
      - code: teacher.attachment
        type: LOCAL
        serve-mode: DIRECT
        path: teacher-attachments
        base-url: http://127.0.0.1:9991/api/admin/resource/file/teacher-attachments
        naming: ORIGINAL
        path-strategy: BIZ_DATE
        exts: [png, jpg, jpeg, webp, gif, pdf, doc, docx, xls, xlsx]
        max-size: 10
        # ========= 教师统计 - 富文本编辑器 - 本地模式 =========
      - code: teacher.richtext
        type: LOCAL
        serve-mode: DIRECT
        path: teacher-richtext
        base-url: http://127.0.0.1:9991/api/admin/resource/file/teacher-richtext
        naming: UUID
        path-strategy: DATE
        exts: [png, jpg, jpeg, webp, gif, pdf, doc, docx, xls, xlsx]
        max-size: 5
      # ========= 未指定时代码生成的临时上传文件 - 本地模式 =========
      - code: system.temp
        type: LOCAL
        serve-mode: DIRECT
        path: temp
        base-url: http://127.0.0.1:9991/api/admin/resource/file/temp
        naming: ORIGINAL
        path-strategy: DATE
        exts: [ png, jpg, jpeg, webp, gif, pdf, doc, docx, xls, xlsx ]
        max-size: 10