router:
  whitelist:
    - "/v3/api-docs/**"
    - "/admin/auth/login"
    - "/admin/register"
    - "/admin/sys-dict/dict"
    - "/webjars/**"
    - "/swagger-resources"
    - "/favicon.ico"
    - "/admin/common/**"
    - "/swagger-ui.html"
    - "/admin/www/**"
