# swagger文档配置
knife4j:
  enable: false
  setting:
    language: zh_cn
springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha·
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'admin'
      paths-to-match: '/**'
      packages-to-scan: com.sz.ssoadmin
    - group: 'generator工具'
      paths-to-match: '/**'
      packages-to-scan: com.sz.generator
